name: Build & Deploy Spring app
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    name: Build & Deploy Spring app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Make Gradle executable
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew bootJar
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USER_NAME }}/spring-boot-docker:${{ github.sha }}
      - name: Build to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USER_NAME }}/spring-boot-docker:${{ github.sha }}